// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/department-management-service/internal/domain"
)

// NewDepartmentManagerServiceMock creates a new instance of DepartmentManagerServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentManagerServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentManagerServiceMock {
	mock := &DepartmentManagerServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DepartmentManagerServiceMock is an autogenerated mock type for the DepartmentManagerService type
type DepartmentManagerServiceMock struct {
	mock.Mock
}

type DepartmentManagerServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *DepartmentManagerServiceMock) EXPECT() *DepartmentManagerServiceMock_Expecter {
	return &DepartmentManagerServiceMock_Expecter{mock: &_m.Mock}
}

// CreateNewDepartment provides a mock function for the type DepartmentManagerServiceMock
func (_mock *DepartmentManagerServiceMock) CreateNewDepartment(ctx context.Context, name string, parentID *int64) (*domain.Department, error) {
	ret := _mock.Called(ctx, name, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewDepartment")
	}

	var r0 *domain.Department
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *int64) (*domain.Department, error)); ok {
		return returnFunc(ctx, name, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *int64) *domain.Department); ok {
		r0 = returnFunc(ctx, name, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Department)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *int64) error); ok {
		r1 = returnFunc(ctx, name, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepartmentManagerServiceMock_CreateNewDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewDepartment'
type DepartmentManagerServiceMock_CreateNewDepartment_Call struct {
	*mock.Call
}

// CreateNewDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - parentID *int64
func (_e *DepartmentManagerServiceMock_Expecter) CreateNewDepartment(ctx interface{}, name interface{}, parentID interface{}) *DepartmentManagerServiceMock_CreateNewDepartment_Call {
	return &DepartmentManagerServiceMock_CreateNewDepartment_Call{Call: _e.mock.On("CreateNewDepartment", ctx, name, parentID)}
}

func (_c *DepartmentManagerServiceMock_CreateNewDepartment_Call) Run(run func(ctx context.Context, name string, parentID *int64)) *DepartmentManagerServiceMock_CreateNewDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *DepartmentManagerServiceMock_CreateNewDepartment_Call) Return(department *domain.Department, err error) *DepartmentManagerServiceMock_CreateNewDepartment_Call {
	_c.Call.Return(department, err)
	return _c
}

func (_c *DepartmentManagerServiceMock_CreateNewDepartment_Call) RunAndReturn(run func(ctx context.Context, name string, parentID *int64) (*domain.Department, error)) *DepartmentManagerServiceMock_CreateNewDepartment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNewEmployee provides a mock function for the type DepartmentManagerServiceMock
func (_mock *DepartmentManagerServiceMock) CreateNewEmployee(ctx context.Context, departmentID int64, fullName string, position string, hiredAt *time.Time) (*domain.Employee, error) {
	ret := _mock.Called(ctx, departmentID, fullName, position, hiredAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewEmployee")
	}

	var r0 *domain.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, *time.Time) (*domain.Employee, error)); ok {
		return returnFunc(ctx, departmentID, fullName, position, hiredAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, *time.Time) *domain.Employee); ok {
		r0 = returnFunc(ctx, departmentID, fullName, position, hiredAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, *time.Time) error); ok {
		r1 = returnFunc(ctx, departmentID, fullName, position, hiredAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepartmentManagerServiceMock_CreateNewEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewEmployee'
type DepartmentManagerServiceMock_CreateNewEmployee_Call struct {
	*mock.Call
}

// CreateNewEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - departmentID int64
//   - fullName string
//   - position string
//   - hiredAt *time.Time
func (_e *DepartmentManagerServiceMock_Expecter) CreateNewEmployee(ctx interface{}, departmentID interface{}, fullName interface{}, position interface{}, hiredAt interface{}) *DepartmentManagerServiceMock_CreateNewEmployee_Call {
	return &DepartmentManagerServiceMock_CreateNewEmployee_Call{Call: _e.mock.On("CreateNewEmployee", ctx, departmentID, fullName, position, hiredAt)}
}

func (_c *DepartmentManagerServiceMock_CreateNewEmployee_Call) Run(run func(ctx context.Context, departmentID int64, fullName string, position string, hiredAt *time.Time)) *DepartmentManagerServiceMock_CreateNewEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *DepartmentManagerServiceMock_CreateNewEmployee_Call) Return(employee *domain.Employee, err error) *DepartmentManagerServiceMock_CreateNewEmployee_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *DepartmentManagerServiceMock_CreateNewEmployee_Call) RunAndReturn(run func(ctx context.Context, departmentID int64, fullName string, position string, hiredAt *time.Time) (*domain.Employee, error)) *DepartmentManagerServiceMock_CreateNewEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDepartmentByID provides a mock function for the type DepartmentManagerServiceMock
func (_mock *DepartmentManagerServiceMock) DeleteDepartmentByID(ctx context.Context, id int64, mode string, reassignTo *int64) error {
	ret := _mock.Called(ctx, id, mode, reassignTo)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDepartmentByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *int64) error); ok {
		r0 = returnFunc(ctx, id, mode, reassignTo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DepartmentManagerServiceMock_DeleteDepartmentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDepartmentByID'
type DepartmentManagerServiceMock_DeleteDepartmentByID_Call struct {
	*mock.Call
}

// DeleteDepartmentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - mode string
//   - reassignTo *int64
func (_e *DepartmentManagerServiceMock_Expecter) DeleteDepartmentByID(ctx interface{}, id interface{}, mode interface{}, reassignTo interface{}) *DepartmentManagerServiceMock_DeleteDepartmentByID_Call {
	return &DepartmentManagerServiceMock_DeleteDepartmentByID_Call{Call: _e.mock.On("DeleteDepartmentByID", ctx, id, mode, reassignTo)}
}

func (_c *DepartmentManagerServiceMock_DeleteDepartmentByID_Call) Run(run func(ctx context.Context, id int64, mode string, reassignTo *int64)) *DepartmentManagerServiceMock_DeleteDepartmentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DepartmentManagerServiceMock_DeleteDepartmentByID_Call) Return(err error) *DepartmentManagerServiceMock_DeleteDepartmentByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DepartmentManagerServiceMock_DeleteDepartmentByID_Call) RunAndReturn(run func(ctx context.Context, id int64, mode string, reassignTo *int64) error) *DepartmentManagerServiceMock_DeleteDepartmentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepartmentByID provides a mock function for the type DepartmentManagerServiceMock
func (_mock *DepartmentManagerServiceMock) GetDepartmentByID(ctx context.Context, id int64, depth int, includeEmployees bool) (*domain.DepartmentTree, error) {
	ret := _mock.Called(ctx, id, depth, includeEmployees)

	if len(ret) == 0 {
		panic("no return value specified for GetDepartmentByID")
	}

	var r0 *domain.DepartmentTree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, bool) (*domain.DepartmentTree, error)); ok {
		return returnFunc(ctx, id, depth, includeEmployees)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, bool) *domain.DepartmentTree); ok {
		r0 = returnFunc(ctx, id, depth, includeEmployees)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DepartmentTree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, bool) error); ok {
		r1 = returnFunc(ctx, id, depth, includeEmployees)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepartmentManagerServiceMock_GetDepartmentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepartmentByID'
type DepartmentManagerServiceMock_GetDepartmentByID_Call struct {
	*mock.Call
}

// GetDepartmentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - depth int
//   - includeEmployees bool
func (_e *DepartmentManagerServiceMock_Expecter) GetDepartmentByID(ctx interface{}, id interface{}, depth interface{}, includeEmployees interface{}) *DepartmentManagerServiceMock_GetDepartmentByID_Call {
	return &DepartmentManagerServiceMock_GetDepartmentByID_Call{Call: _e.mock.On("GetDepartmentByID", ctx, id, depth, includeEmployees)}
}

func (_c *DepartmentManagerServiceMock_GetDepartmentByID_Call) Run(run func(ctx context.Context, id int64, depth int, includeEmployees bool)) *DepartmentManagerServiceMock_GetDepartmentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DepartmentManagerServiceMock_GetDepartmentByID_Call) Return(departmentTree *domain.DepartmentTree, err error) *DepartmentManagerServiceMock_GetDepartmentByID_Call {
	_c.Call.Return(departmentTree, err)
	return _c
}

func (_c *DepartmentManagerServiceMock_GetDepartmentByID_Call) RunAndReturn(run func(ctx context.Context, id int64, depth int, includeEmployees bool) (*domain.DepartmentTree, error)) *DepartmentManagerServiceMock_GetDepartmentByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDepartmentByID provides a mock function for the type DepartmentManagerServiceMock
func (_mock *DepartmentManagerServiceMock) UpdateDepartmentByID(ctx context.Context, id int64, namePtr *string, parentID *int64) (*domain.Department, error) {
	ret := _mock.Called(ctx, id, namePtr, parentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDepartmentByID")
	}

	var r0 *domain.Department
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *string, *int64) (*domain.Department, error)); ok {
		return returnFunc(ctx, id, namePtr, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *string, *int64) *domain.Department); ok {
		r0 = returnFunc(ctx, id, namePtr, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Department)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *string, *int64) error); ok {
		r1 = returnFunc(ctx, id, namePtr, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DepartmentManagerServiceMock_UpdateDepartmentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartmentByID'
type DepartmentManagerServiceMock_UpdateDepartmentByID_Call struct {
	*mock.Call
}

// UpdateDepartmentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - namePtr *string
//   - parentID *int64
func (_e *DepartmentManagerServiceMock_Expecter) UpdateDepartmentByID(ctx interface{}, id interface{}, namePtr interface{}, parentID interface{}) *DepartmentManagerServiceMock_UpdateDepartmentByID_Call {
	return &DepartmentManagerServiceMock_UpdateDepartmentByID_Call{Call: _e.mock.On("UpdateDepartmentByID", ctx, id, namePtr, parentID)}
}

func (_c *DepartmentManagerServiceMock_UpdateDepartmentByID_Call) Run(run func(ctx context.Context, id int64, namePtr *string, parentID *int64)) *DepartmentManagerServiceMock_UpdateDepartmentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *DepartmentManagerServiceMock_UpdateDepartmentByID_Call) Return(department *domain.Department, err error) *DepartmentManagerServiceMock_UpdateDepartmentByID_Call {
	_c.Call.Return(department, err)
	return _c
}

func (_c *DepartmentManagerServiceMock_UpdateDepartmentByID_Call) RunAndReturn(run func(ctx context.Context, id int64, namePtr *string, parentID *int64) (*domain.Department, error)) *DepartmentManagerServiceMock_UpdateDepartmentByID_Call {
	_c.Call.Return(run)
	return _c
}
