// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"github.com/vo1dFl0w/department-management-service/internal/domain"
)

// NewPostgresMock creates a new instance of PostgresMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPostgresMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PostgresMock {
	mock := &PostgresMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PostgresMock is an autogenerated mock type for the Postgres type
type PostgresMock struct {
	mock.Mock
}

type PostgresMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PostgresMock) EXPECT() *PostgresMock_Expecter {
	return &PostgresMock_Expecter{mock: &_m.Mock}
}

// CreateDepartment provides a mock function for the type PostgresMock
func (_mock *PostgresMock) CreateDepartment(ctx context.Context, name string, parentID *int64) (*domain.Department, error) {
	ret := _mock.Called(ctx, name, parentID)

	if len(ret) == 0 {
		panic("no return value specified for CreateDepartment")
	}

	var r0 *domain.Department
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *int64) (*domain.Department, error)); ok {
		return returnFunc(ctx, name, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *int64) *domain.Department); ok {
		r0 = returnFunc(ctx, name, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Department)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *int64) error); ok {
		r1 = returnFunc(ctx, name, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresMock_CreateDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDepartment'
type PostgresMock_CreateDepartment_Call struct {
	*mock.Call
}

// CreateDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - parentID *int64
func (_e *PostgresMock_Expecter) CreateDepartment(ctx interface{}, name interface{}, parentID interface{}) *PostgresMock_CreateDepartment_Call {
	return &PostgresMock_CreateDepartment_Call{Call: _e.mock.On("CreateDepartment", ctx, name, parentID)}
}

func (_c *PostgresMock_CreateDepartment_Call) Run(run func(ctx context.Context, name string, parentID *int64)) *PostgresMock_CreateDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *int64
		if args[2] != nil {
			arg2 = args[2].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *PostgresMock_CreateDepartment_Call) Return(department *domain.Department, err error) *PostgresMock_CreateDepartment_Call {
	_c.Call.Return(department, err)
	return _c
}

func (_c *PostgresMock_CreateDepartment_Call) RunAndReturn(run func(ctx context.Context, name string, parentID *int64) (*domain.Department, error)) *PostgresMock_CreateDepartment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEmployee provides a mock function for the type PostgresMock
func (_mock *PostgresMock) CreateEmployee(ctx context.Context, departmentID int64, fullName string, position string, hiredAt *time.Time) (*domain.Employee, error) {
	ret := _mock.Called(ctx, departmentID, fullName, position, hiredAt)

	if len(ret) == 0 {
		panic("no return value specified for CreateEmployee")
	}

	var r0 *domain.Employee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, *time.Time) (*domain.Employee, error)); ok {
		return returnFunc(ctx, departmentID, fullName, position, hiredAt)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, string, *time.Time) *domain.Employee); ok {
		r0 = returnFunc(ctx, departmentID, fullName, position, hiredAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Employee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, string, string, *time.Time) error); ok {
		r1 = returnFunc(ctx, departmentID, fullName, position, hiredAt)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresMock_CreateEmployee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEmployee'
type PostgresMock_CreateEmployee_Call struct {
	*mock.Call
}

// CreateEmployee is a helper method to define mock.On call
//   - ctx context.Context
//   - departmentID int64
//   - fullName string
//   - position string
//   - hiredAt *time.Time
func (_e *PostgresMock_Expecter) CreateEmployee(ctx interface{}, departmentID interface{}, fullName interface{}, position interface{}, hiredAt interface{}) *PostgresMock_CreateEmployee_Call {
	return &PostgresMock_CreateEmployee_Call{Call: _e.mock.On("CreateEmployee", ctx, departmentID, fullName, position, hiredAt)}
}

func (_c *PostgresMock_CreateEmployee_Call) Run(run func(ctx context.Context, departmentID int64, fullName string, position string, hiredAt *time.Time)) *PostgresMock_CreateEmployee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *PostgresMock_CreateEmployee_Call) Return(employee *domain.Employee, err error) *PostgresMock_CreateEmployee_Call {
	_c.Call.Return(employee, err)
	return _c
}

func (_c *PostgresMock_CreateEmployee_Call) RunAndReturn(run func(ctx context.Context, departmentID int64, fullName string, position string, hiredAt *time.Time) (*domain.Employee, error)) *PostgresMock_CreateEmployee_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDepartment provides a mock function for the type PostgresMock
func (_mock *PostgresMock) DeleteDepartment(ctx context.Context, id int64, mode string, reassignTo *int64) error {
	ret := _mock.Called(ctx, id, mode, reassignTo)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDepartment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, *int64) error); ok {
		r0 = returnFunc(ctx, id, mode, reassignTo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// PostgresMock_DeleteDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDepartment'
type PostgresMock_DeleteDepartment_Call struct {
	*mock.Call
}

// DeleteDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - mode string
//   - reassignTo *int64
func (_e *PostgresMock_Expecter) DeleteDepartment(ctx interface{}, id interface{}, mode interface{}, reassignTo interface{}) *PostgresMock_DeleteDepartment_Call {
	return &PostgresMock_DeleteDepartment_Call{Call: _e.mock.On("DeleteDepartment", ctx, id, mode, reassignTo)}
}

func (_c *PostgresMock_DeleteDepartment_Call) Run(run func(ctx context.Context, id int64, mode string, reassignTo *int64)) *PostgresMock_DeleteDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PostgresMock_DeleteDepartment_Call) Return(err error) *PostgresMock_DeleteDepartment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *PostgresMock_DeleteDepartment_Call) RunAndReturn(run func(ctx context.Context, id int64, mode string, reassignTo *int64) error) *PostgresMock_DeleteDepartment_Call {
	_c.Call.Return(run)
	return _c
}

// GetDepartment provides a mock function for the type PostgresMock
func (_mock *PostgresMock) GetDepartment(ctx context.Context, id int64, depth int, includeEmployees bool) (*domain.DepartmentTree, error) {
	ret := _mock.Called(ctx, id, depth, includeEmployees)

	if len(ret) == 0 {
		panic("no return value specified for GetDepartment")
	}

	var r0 *domain.DepartmentTree
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, bool) (*domain.DepartmentTree, error)); ok {
		return returnFunc(ctx, id, depth, includeEmployees)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int, bool) *domain.DepartmentTree); ok {
		r0 = returnFunc(ctx, id, depth, includeEmployees)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DepartmentTree)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int, bool) error); ok {
		r1 = returnFunc(ctx, id, depth, includeEmployees)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresMock_GetDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDepartment'
type PostgresMock_GetDepartment_Call struct {
	*mock.Call
}

// GetDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - depth int
//   - includeEmployees bool
func (_e *PostgresMock_Expecter) GetDepartment(ctx interface{}, id interface{}, depth interface{}, includeEmployees interface{}) *PostgresMock_GetDepartment_Call {
	return &PostgresMock_GetDepartment_Call{Call: _e.mock.On("GetDepartment", ctx, id, depth, includeEmployees)}
}

func (_c *PostgresMock_GetDepartment_Call) Run(run func(ctx context.Context, id int64, depth int, includeEmployees bool)) *PostgresMock_GetDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PostgresMock_GetDepartment_Call) Return(departmentTree *domain.DepartmentTree, err error) *PostgresMock_GetDepartment_Call {
	_c.Call.Return(departmentTree, err)
	return _c
}

func (_c *PostgresMock_GetDepartment_Call) RunAndReturn(run func(ctx context.Context, id int64, depth int, includeEmployees bool) (*domain.DepartmentTree, error)) *PostgresMock_GetDepartment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDepartment provides a mock function for the type PostgresMock
func (_mock *PostgresMock) UpdateDepartment(ctx context.Context, id int64, namePtr *string, parentID *int64) (*domain.Department, error) {
	ret := _mock.Called(ctx, id, namePtr, parentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDepartment")
	}

	var r0 *domain.Department
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *string, *int64) (*domain.Department, error)); ok {
		return returnFunc(ctx, id, namePtr, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, *string, *int64) *domain.Department); ok {
		r0 = returnFunc(ctx, id, namePtr, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Department)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, *string, *int64) error); ok {
		r1 = returnFunc(ctx, id, namePtr, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PostgresMock_UpdateDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartment'
type PostgresMock_UpdateDepartment_Call struct {
	*mock.Call
}

// UpdateDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - namePtr *string
//   - parentID *int64
func (_e *PostgresMock_Expecter) UpdateDepartment(ctx interface{}, id interface{}, namePtr interface{}, parentID interface{}) *PostgresMock_UpdateDepartment_Call {
	return &PostgresMock_UpdateDepartment_Call{Call: _e.mock.On("UpdateDepartment", ctx, id, namePtr, parentID)}
}

func (_c *PostgresMock_UpdateDepartment_Call) Run(run func(ctx context.Context, id int64, namePtr *string, parentID *int64)) *PostgresMock_UpdateDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *PostgresMock_UpdateDepartment_Call) Return(department *domain.Department, err error) *PostgresMock_UpdateDepartment_Call {
	_c.Call.Return(department, err)
	return _c
}

func (_c *PostgresMock_UpdateDepartment_Call) RunAndReturn(run func(ctx context.Context, id int64, namePtr *string, parentID *int64) (*domain.Department, error)) *PostgresMock_UpdateDepartment_Call {
	_c.Call.Return(run)
	return _c
}
