// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"time"

	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CreateDepartmentRequest
type CreateDepartmentRequest struct {
	Name string `json:"name"`
	// Parent department id (nullable for root).
	ParentID OptNilInt `json:"parent_id"`
}

// GetName returns the value of Name.
func (s *CreateDepartmentRequest) GetName() string {
	return s.Name
}

// GetParentID returns the value of ParentID.
func (s *CreateDepartmentRequest) GetParentID() OptNilInt {
	return s.ParentID
}

// SetName sets the value of Name.
func (s *CreateDepartmentRequest) SetName(val string) {
	s.Name = val
}

// SetParentID sets the value of ParentID.
func (s *CreateDepartmentRequest) SetParentID(val OptNilInt) {
	s.ParentID = val
}

// Ref: #/components/schemas/CreateEmployeeRequest
type CreateEmployeeRequest struct {
	FullName string `json:"full_name"`
	Position string `json:"position"`
	// Hire date (YYYY-MM-DD), optional.
	HiredAt OptNilDate `json:"hired_at"`
}

// GetFullName returns the value of FullName.
func (s *CreateEmployeeRequest) GetFullName() string {
	return s.FullName
}

// GetPosition returns the value of Position.
func (s *CreateEmployeeRequest) GetPosition() string {
	return s.Position
}

// GetHiredAt returns the value of HiredAt.
func (s *CreateEmployeeRequest) GetHiredAt() OptNilDate {
	return s.HiredAt
}

// SetFullName sets the value of FullName.
func (s *CreateEmployeeRequest) SetFullName(val string) {
	s.FullName = val
}

// SetPosition sets the value of Position.
func (s *CreateEmployeeRequest) SetPosition(val string) {
	s.Position = val
}

// SetHiredAt sets the value of HiredAt.
func (s *CreateEmployeeRequest) SetHiredAt(val OptNilDate) {
	s.HiredAt = val
}

// Ref: #/components/schemas/Department
type Department struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	ParentID  OptNilInt `json:"parent_id"`
	CreatedAt time.Time `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Department) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Department) GetName() string {
	return s.Name
}

// GetParentID returns the value of ParentID.
func (s *Department) GetParentID() OptNilInt {
	return s.ParentID
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Department) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Department) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Department) SetName(val string) {
	s.Name = val
}

// SetParentID sets the value of ParentID.
func (s *Department) SetParentID(val OptNilInt) {
	s.ParentID = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Department) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Department) departmentsIDPatchRes() {}
func (*Department) departmentsPostRes()    {}

// Ref: #/components/schemas/DepartmentWithChildrenAndEmployees
type DepartmentWithChildrenAndEmployees struct {
	Department Department `json:"department"`
	// List of employees in this department. Returned only if include_employees=true. Server must sort by
	// created_at or full_name.
	Employees []Employee `json:"employees"`
	// Recursive list of child departments up to requested depth.
	Children []DepartmentWithChildrenAndEmployees `json:"children"`
}

// GetDepartment returns the value of Department.
func (s *DepartmentWithChildrenAndEmployees) GetDepartment() Department {
	return s.Department
}

// GetEmployees returns the value of Employees.
func (s *DepartmentWithChildrenAndEmployees) GetEmployees() []Employee {
	return s.Employees
}

// GetChildren returns the value of Children.
func (s *DepartmentWithChildrenAndEmployees) GetChildren() []DepartmentWithChildrenAndEmployees {
	return s.Children
}

// SetDepartment sets the value of Department.
func (s *DepartmentWithChildrenAndEmployees) SetDepartment(val Department) {
	s.Department = val
}

// SetEmployees sets the value of Employees.
func (s *DepartmentWithChildrenAndEmployees) SetEmployees(val []Employee) {
	s.Employees = val
}

// SetChildren sets the value of Children.
func (s *DepartmentWithChildrenAndEmployees) SetChildren(val []DepartmentWithChildrenAndEmployees) {
	s.Children = val
}

func (*DepartmentWithChildrenAndEmployees) departmentsIDGetRes() {}

type DepartmentsIDDeleteBadRequest ErrorResponse

func (*DepartmentsIDDeleteBadRequest) departmentsIDDeleteRes() {}

type DepartmentsIDDeleteConflict ErrorResponse

func (*DepartmentsIDDeleteConflict) departmentsIDDeleteRes() {}

type DepartmentsIDDeleteGatewayTimeout ErrorResponse

func (*DepartmentsIDDeleteGatewayTimeout) departmentsIDDeleteRes() {}

type DepartmentsIDDeleteInternalServerError ErrorResponse

func (*DepartmentsIDDeleteInternalServerError) departmentsIDDeleteRes() {}

type DepartmentsIDDeleteMode string

const (
	DepartmentsIDDeleteModeCascade  DepartmentsIDDeleteMode = "cascade"
	DepartmentsIDDeleteModeReassign DepartmentsIDDeleteMode = "reassign"
)

// AllValues returns all DepartmentsIDDeleteMode values.
func (DepartmentsIDDeleteMode) AllValues() []DepartmentsIDDeleteMode {
	return []DepartmentsIDDeleteMode{
		DepartmentsIDDeleteModeCascade,
		DepartmentsIDDeleteModeReassign,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s DepartmentsIDDeleteMode) MarshalText() ([]byte, error) {
	switch s {
	case DepartmentsIDDeleteModeCascade:
		return []byte(s), nil
	case DepartmentsIDDeleteModeReassign:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *DepartmentsIDDeleteMode) UnmarshalText(data []byte) error {
	switch DepartmentsIDDeleteMode(data) {
	case DepartmentsIDDeleteModeCascade:
		*s = DepartmentsIDDeleteModeCascade
		return nil
	case DepartmentsIDDeleteModeReassign:
		*s = DepartmentsIDDeleteModeReassign
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// DepartmentsIDDeleteNoContent is response for DepartmentsIDDelete operation.
type DepartmentsIDDeleteNoContent struct{}

func (*DepartmentsIDDeleteNoContent) departmentsIDDeleteRes() {}

type DepartmentsIDDeleteNotFound ErrorResponse

func (*DepartmentsIDDeleteNotFound) departmentsIDDeleteRes() {}

type DepartmentsIDEmployeesPostBadRequest ErrorResponse

func (*DepartmentsIDEmployeesPostBadRequest) departmentsIDEmployeesPostRes() {}

type DepartmentsIDEmployeesPostGatewayTimeout ErrorResponse

func (*DepartmentsIDEmployeesPostGatewayTimeout) departmentsIDEmployeesPostRes() {}

type DepartmentsIDEmployeesPostInternalServerError ErrorResponse

func (*DepartmentsIDEmployeesPostInternalServerError) departmentsIDEmployeesPostRes() {}

type DepartmentsIDEmployeesPostNotFound ErrorResponse

func (*DepartmentsIDEmployeesPostNotFound) departmentsIDEmployeesPostRes() {}

type DepartmentsIDGetBadRequest ErrorResponse

func (*DepartmentsIDGetBadRequest) departmentsIDGetRes() {}

type DepartmentsIDGetGatewayTimeout ErrorResponse

func (*DepartmentsIDGetGatewayTimeout) departmentsIDGetRes() {}

type DepartmentsIDGetInternalServerError ErrorResponse

func (*DepartmentsIDGetInternalServerError) departmentsIDGetRes() {}

type DepartmentsIDGetNotFound ErrorResponse

func (*DepartmentsIDGetNotFound) departmentsIDGetRes() {}

type DepartmentsIDPatchBadRequest ErrorResponse

func (*DepartmentsIDPatchBadRequest) departmentsIDPatchRes() {}

type DepartmentsIDPatchConflict ErrorResponse

func (*DepartmentsIDPatchConflict) departmentsIDPatchRes() {}

type DepartmentsIDPatchGatewayTimeout ErrorResponse

func (*DepartmentsIDPatchGatewayTimeout) departmentsIDPatchRes() {}

type DepartmentsIDPatchInternalServerError ErrorResponse

func (*DepartmentsIDPatchInternalServerError) departmentsIDPatchRes() {}

type DepartmentsIDPatchNotFound ErrorResponse

func (*DepartmentsIDPatchNotFound) departmentsIDPatchRes() {}

type DepartmentsPostBadRequest ErrorResponse

func (*DepartmentsPostBadRequest) departmentsPostRes() {}

type DepartmentsPostConflict ErrorResponse

func (*DepartmentsPostConflict) departmentsPostRes() {}

type DepartmentsPostGatewayTimeout ErrorResponse

func (*DepartmentsPostGatewayTimeout) departmentsPostRes() {}

type DepartmentsPostInternalServerError ErrorResponse

func (*DepartmentsPostInternalServerError) departmentsPostRes() {}

type DepartmentsPostNotFound ErrorResponse

func (*DepartmentsPostNotFound) departmentsPostRes() {}

// Ref: #/components/schemas/Employee
type Employee struct {
	ID           int        `json:"id"`
	DepartmentID int        `json:"department_id"`
	FullName     string     `json:"full_name"`
	Position     string     `json:"position"`
	HiredAt      OptNilDate `json:"hired_at"`
	CreatedAt    time.Time  `json:"created_at"`
}

// GetID returns the value of ID.
func (s *Employee) GetID() int {
	return s.ID
}

// GetDepartmentID returns the value of DepartmentID.
func (s *Employee) GetDepartmentID() int {
	return s.DepartmentID
}

// GetFullName returns the value of FullName.
func (s *Employee) GetFullName() string {
	return s.FullName
}

// GetPosition returns the value of Position.
func (s *Employee) GetPosition() string {
	return s.Position
}

// GetHiredAt returns the value of HiredAt.
func (s *Employee) GetHiredAt() OptNilDate {
	return s.HiredAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Employee) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *Employee) SetID(val int) {
	s.ID = val
}

// SetDepartmentID sets the value of DepartmentID.
func (s *Employee) SetDepartmentID(val int) {
	s.DepartmentID = val
}

// SetFullName sets the value of FullName.
func (s *Employee) SetFullName(val string) {
	s.FullName = val
}

// SetPosition sets the value of Position.
func (s *Employee) SetPosition(val string) {
	s.Position = val
}

// SetHiredAt sets the value of HiredAt.
func (s *Employee) SetHiredAt(val OptNilDate) {
	s.HiredAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Employee) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

func (*Employee) departmentsIDEmployeesPostRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Status  int    `json:"status"`
	Message string `json:"message"`
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() int {
	return s.Status
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val int) {
	s.Status = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDate returns new OptNilDate with value set to v.
func NewOptNilDate(v time.Time) OptNilDate {
	return OptNilDate{
		Value: v,
		Set:   true,
	}
}

// OptNilDate is optional nullable time.Time.
type OptNilDate struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDate was set.
func (o OptNilDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDate) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDate) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDate) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDate) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/UpdateDepartmentRequest
type UpdateDepartmentRequest struct {
	// New name for the current department (rename). Not a reference to another department.
	Name OptString `json:"name"`
	// New parent department id (nullable to move to root). Server must validate to avoid cycles.
	ParentID OptNilInt `json:"parent_id"`
}

// GetName returns the value of Name.
func (s *UpdateDepartmentRequest) GetName() OptString {
	return s.Name
}

// GetParentID returns the value of ParentID.
func (s *UpdateDepartmentRequest) GetParentID() OptNilInt {
	return s.ParentID
}

// SetName sets the value of Name.
func (s *UpdateDepartmentRequest) SetName(val OptString) {
	s.Name = val
}

// SetParentID sets the value of ParentID.
func (s *UpdateDepartmentRequest) SetParentID(val OptNilInt) {
	s.ParentID = val
}
