// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DepartmentsIDDelete implements DELETE /departments/{id} operation.
//
// Delete a department. Two modes: - cascade — delete department, all its employees and child
// departments - reassign — delete department, reassign employees to `reassign_to_department_id`
// (this query param is required when mode=reassign).
//
// DELETE /departments/{id}
func (UnimplementedHandler) DepartmentsIDDelete(ctx context.Context, params DepartmentsIDDeleteParams) (r DepartmentsIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DepartmentsIDEmployeesPost implements POST /departments/{id}/employees/ operation.
//
// Creates a new employee and assigns them to department {id}.
//
// POST /departments/{id}/employees/
func (UnimplementedHandler) DepartmentsIDEmployeesPost(ctx context.Context, req *CreateEmployeeRequest, params DepartmentsIDEmployeesPostParams) (r DepartmentsIDEmployeesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DepartmentsIDGet implements GET /departments/{id} operation.
//
// Return department details. `depth` controls recursion depth for children (default 1, max 5). If
// include_employees=true employees are included (server sorts by created_at or full_name).
//
// GET /departments/{id}
func (UnimplementedHandler) DepartmentsIDGet(ctx context.Context, params DepartmentsIDGetParams) (r DepartmentsIDGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DepartmentsIDPatch implements PATCH /departments/{id} operation.
//
// Partial update: provide one or both fields. `name` = new name of the current department (rename).
// `parent_id` = target parent id (nullable to move to root). Server must prevent cycles (409).
//
// PATCH /departments/{id}
func (UnimplementedHandler) DepartmentsIDPatch(ctx context.Context, req *UpdateDepartmentRequest, params DepartmentsIDPatchParams) (r DepartmentsIDPatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DepartmentsPost implements POST /departments/ operation.
//
// Create a department with a name and optional parent (parent_id nullable for root).
//
// POST /departments/
func (UnimplementedHandler) DepartmentsPost(ctx context.Context, req *CreateDepartmentRequest) (r DepartmentsPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
