// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// DepartmentsIDDelete implements DELETE /departments/{id} operation.
	//
	// Delete a department. Two modes: - cascade — delete department, all its employees and child
	// departments - reassign — delete department, reassign employees to `reassign_to_department_id`
	// (this query param is required when mode=reassign).
	//
	// DELETE /departments/{id}
	DepartmentsIDDelete(ctx context.Context, params DepartmentsIDDeleteParams) (DepartmentsIDDeleteRes, error)
	// DepartmentsIDEmployeesPost implements POST /departments/{id}/employees/ operation.
	//
	// Creates a new employee and assigns them to department {id}.
	//
	// POST /departments/{id}/employees/
	DepartmentsIDEmployeesPost(ctx context.Context, req *CreateEmployeeRequest, params DepartmentsIDEmployeesPostParams) (DepartmentsIDEmployeesPostRes, error)
	// DepartmentsIDGet implements GET /departments/{id} operation.
	//
	// Return department details. `depth` controls recursion depth for children (default 1, max 5). If
	// include_employees=true employees are included (server sorts by created_at or full_name).
	//
	// GET /departments/{id}
	DepartmentsIDGet(ctx context.Context, params DepartmentsIDGetParams) (DepartmentsIDGetRes, error)
	// DepartmentsIDPatch implements PATCH /departments/{id} operation.
	//
	// Partial update: provide one or both fields. `name` = new name of the current department (rename).
	// `parent_id` = target parent id (nullable to move to root). Server must prevent cycles (409).
	//
	// PATCH /departments/{id}
	DepartmentsIDPatch(ctx context.Context, req *UpdateDepartmentRequest, params DepartmentsIDPatchParams) (DepartmentsIDPatchRes, error)
	// DepartmentsPost implements POST /departments/ operation.
	//
	// Create a department with a name and optional parent (parent_id nullable for root).
	//
	// POST /departments/
	DepartmentsPost(ctx context.Context, req *CreateDepartmentRequest) (DepartmentsPostRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
