// Code generated by ogen, DO NOT EDIT.

package httpgen

// OperationName is the ogen operation name
type OperationName = string

const (
	DepartmentsIDDeleteOperation        OperationName = "DepartmentsIDDelete"
	DepartmentsIDEmployeesPostOperation OperationName = "DepartmentsIDEmployeesPost"
	DepartmentsIDGetOperation           OperationName = "DepartmentsIDGet"
	DepartmentsIDPatchOperation         OperationName = "DepartmentsIDPatch"
	DepartmentsPostOperation            OperationName = "DepartmentsPost"
)
