// Code generated by ogen, DO NOT EDIT.

package httpgen

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DepartmentsIDDeleteParams is parameters of DELETE /departments/{id} operation.
type DepartmentsIDDeleteParams struct {
	ID int
	// Delete mode (default: cascade).
	Mode DepartmentsIDDeleteMode
	// Target department id to reassign employees when mode=reassign. REQUIRED when mode=reassign.
	ReassignToDepartmentID OptInt `json:",omitempty,omitzero"`
}

func unpackDepartmentsIDDeleteParams(packed middleware.Parameters) (params DepartmentsIDDeleteParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "mode",
			In:   "query",
		}
		params.Mode = packed[key].(DepartmentsIDDeleteMode)
	}
	{
		key := middleware.ParameterKey{
			Name: "reassign_to_department_id",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.ReassignToDepartmentID = v.(OptInt)
		}
	}
	return params
}

func decodeDepartmentsIDDeleteParams(args [1]string, argsEscaped bool, r *http.Request) (params DepartmentsIDDeleteParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: mode.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "mode",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Mode = DepartmentsIDDeleteMode(c)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.Mode.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "mode",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: reassign_to_department_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "reassign_to_department_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotReassignToDepartmentIDVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotReassignToDepartmentIDVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ReassignToDepartmentID.SetTo(paramsDotReassignToDepartmentIDVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "reassign_to_department_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DepartmentsIDEmployeesPostParams is parameters of POST /departments/{id}/employees/ operation.
type DepartmentsIDEmployeesPostParams struct {
	// Department id to assign the employee to.
	ID int
}

func unpackDepartmentsIDEmployeesPostParams(packed middleware.Parameters) (params DepartmentsIDEmployeesPostParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeDepartmentsIDEmployeesPostParams(args [1]string, argsEscaped bool, r *http.Request) (params DepartmentsIDEmployeesPostParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DepartmentsIDGetParams is parameters of GET /departments/{id} operation.
type DepartmentsIDGetParams struct {
	ID int
	// Depth of nested child departments to include (default: 1, max: 5).
	Depth OptInt `json:",omitempty,omitzero"`
	// Whether to include employees in the response (default: true).
	IncludeEmployees OptBool `json:",omitempty,omitzero"`
}

func unpackDepartmentsIDGetParams(packed middleware.Parameters) (params DepartmentsIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	{
		key := middleware.ParameterKey{
			Name: "depth",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Depth = v.(OptInt)
		}
	}
	{
		key := middleware.ParameterKey{
			Name: "include_employees",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.IncludeEmployees = v.(OptBool)
		}
	}
	return params
}

func decodeDepartmentsIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params DepartmentsIDGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Set default value for query: depth.
	{
		val := int(1)
		params.Depth.SetTo(val)
	}
	// Decode query: depth.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "depth",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotDepthVal int
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToInt(val)
					if err != nil {
						return err
					}

					paramsDotDepthVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Depth.SetTo(paramsDotDepthVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Depth.Get(); ok {
					if err := func() error {
						if err := (validate.Int{
							MinSet:        true,
							Min:           0,
							MaxSet:        true,
							Max:           5,
							MinExclusive:  false,
							MaxExclusive:  false,
							MultipleOfSet: false,
							MultipleOf:    0,
							Pattern:       nil,
						}).Validate(int64(value)); err != nil {
							return errors.Wrap(err, "int")
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "depth",
			In:   "query",
			Err:  err,
		}
	}
	// Set default value for query: include_employees.
	{
		val := bool(true)
		params.IncludeEmployees.SetTo(val)
	}
	// Decode query: include_employees.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "include_employees",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIncludeEmployeesVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotIncludeEmployeesVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IncludeEmployees.SetTo(paramsDotIncludeEmployeesVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "include_employees",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DepartmentsIDPatchParams is parameters of PATCH /departments/{id} operation.
type DepartmentsIDPatchParams struct {
	ID int
}

func unpackDepartmentsIDPatchParams(packed middleware.Parameters) (params DepartmentsIDPatchParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(int)
	}
	return params
}

func decodeDepartmentsIDPatchParams(args [1]string, argsEscaped bool, r *http.Request) (params DepartmentsIDPatchParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
