// Code generated by ogen, DO NOT EDIT.
package httpgen

type DepartmentsIDDeleteRes interface {
	departmentsIDDeleteRes()
}

type DepartmentsIDEmployeesPostRes interface {
	departmentsIDEmployeesPostRes()
}

type DepartmentsIDGetRes interface {
	departmentsIDGetRes()
}

type DepartmentsIDPatchRes interface {
	departmentsIDPatchRes()
}

type DepartmentsPostRes interface {
	departmentsPostRes()
}
